sudo: required

language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

notifications:
   on_success: never
   on_failure: always

matrix:
  fast_finish: true

env:
  global:
    - GIT_BRANCH: master

install:
  # install Composer dependencies
  - cd application && composer install --prefer-dist && cd ..

before_script:
  - composer self-update

script:
  # run the tests
  - make tests
