version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: ${CONTAINER_NAME_PREFIX}-redis

    mysql:
      image: mysql:5.7
      container_name: ${CONTAINER_NAME_PREFIX}-mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_TEST_DATABASE: ${DB_TEST_NAME}

    webserver:
      image: nginx:alpine
      container_name: ${CONTAINER_NAME_PREFIX}-nignx
      working_dir: /var/www/html
      links:
        - php-fpm
      volumes:
          - ./application:/var/www/html
          - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: docker/php-fpm
      container_name: ${CONTAINER_NAME_PREFIX}-php-fpm
      working_dir: /var/www/html
      links:
        - mysql
      volumes:
        - ./application:/var/www/html
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini