parameters:
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     pet_test
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~
    mailer_port:       25

    redis_host:        127.0.0.1
    redis_port:        ~

    # A secret key that's used to generate certain security-related tokens
    kernel.secret:            ThisTokenIsNotSoSecretChangeIt
